[workspace]
resolver = "3"
members = ["client","daemon", "gui", "wallpapers"]
default-members = ["client","daemon", "wallpapers"]

[workspace.package]
version = "0.1.0-unstable.0"
authors = ["Melissa Vernigorenko"]
edition = "2024"
license = "MIT"
description = "A powerful wallpaper manager for unix"
readme = "README.md"
repository = "https://codeberg.org/silverfairies/wallie"

[profile.dev.package."*"]
opt-level = 3
codegen-units = 1

[profile.release]
panic = "abort"
lto = "fat"
codegen-units = 1
strip = true
debug = 0
opt-level = "z"
