[package]
name = "wallie-daemon"
version.workspace = true
authors.workspace = true
edition.workspace = true
license.workspace = true

[dependencies]
interprocess = { version = "2.4.2", default-features = false }
rand = { version = "0.10.2", default-features = false, features = ["std", "std_rng", "sys_rng"] }
serde = { version = "1.0.229", default-features = false, features = ["std"] }
